send_notification:
  name: Send Notification
  description: Send a notification to the LaxasFit watch screen.
  target:
    device:
      integration: laxasfit
  fields:
    message:
      name: Message
      description: The notification message to display on the watch.
      required: true
      selector:
        text:
    title:
      name: Title
      description: Title/prefix of the notification.
      default: "HA"
      selector:
        text:
    type:
      name: Type
      description: Notification type (sms, whatsapp, telegram, etc).
      default: "other"
      selector:
        select:
          options:
            - "sms"
            - "whatsapp"
            - "telegram"
            - "instagram"
            - "facebook"
            - "twitter"
            - "skype"
            - "line"
            - "viber"
            - "other"
